---
- hosts: mylaptop
  become: sudo
  tasks:
  - name: ensure apache is installed and up to date
    apt: name=apache2 state=latest
  - name: write the apache config file
    file: src=apache2.conf dest=/etc/apache2/apache2.conf
    notify:
    - restart apache
  - name: apache is running (and enable it at boot)
    service: name=apache2 state=started enabled=yes
  handlers:
  - name: restart apache
    service: name=apache2 state=restarted


